version: "3.8"

services:
  # Ory Kratos Server
  ory_kratos_trials2:
    image: oryd/kratos:v1.0.0
    container_name: ory_kratos_trials2
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    depends_on:
      - ory_kratos_trials2_migrate
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ory_hydra_trials2_postgresd:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve all --dev --watch-courier
    # volumes:
    #   - type: volume
    #     source: pgdata
    #     target: /var/lib/sqlite
    #     read_only: false
    #   - type: bind
    #     source: ./contrib/quickstart/kratos/email-password
    #     target: /etc/config/kratos
    networks:
      - ory_kratos_trials2_network

  # Ory Kratos Migrator
  ory_kratos_trials2_migrate:
    image: oryd/kratos:v1.0.0
    container_name: ory_kratos_trials2_migrate
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ory_hydra_trials2_postgresd:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./contrib/quickstart/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - ory_kratos_trials2_network

  # Simple UI for Kratos
  ory_kratos_trials2_node_ui:
    image: oryd/kratos-selfservice-ui-node:v1.0.0
    container_name: ory_kratos_trials2_node_ui
    environment:
      - KRATOS_PUBLIC_URL=http://ory_kratos_trials2:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    networks:
      - ory_kratos_trials2_network
    restart: on-failure

  # SMTP Mail Server for Testing
  ory_mailslurper_trials2:
    image: oryd/mailslurper:latest-smtps
    container_name: ory_ailslurper_trials2
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - ory_kratos_trials2_network

  # Ory Kratos Database
  ory_kratos_trials2_postgresd:
    image: postgres:15
    container_name: ory_kratos_trials2_postgresd
    restart: on-failure
    networks:
      - ory_kratos_trials2_network
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  ory_kratos_trials2_network:
    name: ory-kratos-net

volumes:
  pgdata:
